name: SkillIssue
main: org.limestick.skillissue.SkillIssue
version: 0.2
description: Difficulty back-ported to CB1060
commands:
    difficulty:
        description: Change the game difficulty settings.
        usage: /<command> <peaceful|easy|normal|hard|custom> - /<command> set <property> <value>
        permission: skillissue.difficulty
permissions:
    skillissue.*:
        description: Permission for all SkillIssue commands.
        default: op
        children:
            skillissue.difficulty: false
    skillissue.difficulty:
        description: Permission to set the difficulty.
        default: op